### ISSUE TITLE
"emergency shell: unable to mount rpool/ROOT/pve1"

### ISSUE THREAD

**Issue by churipputori** [midzelis/zquickinit#7]
Installed zquickinit 1.0.5 via injected efi file. After full wipe and install to new encrypted pool, first boot fails with the error "emergency shell: unable to mount rpool/ROOT/pve1    /boot/vmlinuz-6.8.4-3-pve    /boot/initrd.img-6.8.4-3-pve". That is all the error that is given. Neither ZFSBootMenu logs nor dmesg show any information regarding this error either.

**Comment by midzelis** [comment]
Hey - give it another go. I've made a bunch of improvements.

**Comment by midzelis** [comment]
Fixed via #11
