### ISSUE TITLE
Bare-metal install: failure during "Running bootstrap"

### ISSUE THREAD

**Issue by luispabon** [midzelis/zquickinit#9]
Apologies for the screenshot, unable to copy&paste:

![image](https://github.com/user-attachments/assets/cf757df1-2a1d-4075-8ae9-28b5b000b2ff)

Looks like the ftp archive does not keep historical files, or they sometimes get deleted. 

Current is https://ftp.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.137.tar.gz

**Comment by midzelis** [comment]
Fixed via #11
